# Use the official Gradle image to create a build artifact.
FROM gradle:7.4.0-jdk11 as builder

# Set the working directory in the container
WORKDIR /app

# Copy the Gradle configuration files separately to leverage Docker cache layering
COPY build.gradle.kts settings.gradle.kts /app/

# Copy the source code
COPY src /app/src

# Run the Gradle build command to build the application
RUN gradle clean build --no-daemon

# Use OpenJDK for running the application.
FROM openjdk:11-jre-slim

# Set deployment directory
WORKDIR /app

# Copy only the built artifact and ignore all other build artifacts and metadata generated by Gradle
COPY --from=builder /app/build/libs/*.jar /app/app.jar

# Expose port 8080 for the web server
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]
