version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transactions_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: transactions_db
    volumes:
      - postgres_transactions_data:/var/lib/postgresql/data
    networks:
      - transactions_net

  transactions-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transactions_db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
    depends_on:
      - postgres
    networks:
      - transactions_net

volumes:
  postgres_transactions_data:

networks:
  transactions_net:
